name: Build and Test

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pythong
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: apt install meson ninja
      - name: Configure project
        working-directory: ./tests
        run: meson setup testdir
        env:
          CC: gcc
      - name: Ninja build
        working-directory: ./tests/testdir
        run: ninja
      - name: Run tests
        working-directory: ./tests/testdir
        run: ./tests
